

#ifndef _RTE_STUB_CALPRM_X_H
#define _RTE_STUB_CALPRM_X_H

#ifdef __cplusplus
extern "C"
{
#endif

ImpTypeValCRdciCorHoldOffTime Stub_Rte_Prm_CRdciCorHoldOffTime(void);
ImpTypeValCRdciDefaultLoadCond Stub_Rte_Prm_CRdciDefaultLoadCond(void);
ImpTypeValCRdciDefaultMenuSel Stub_Rte_Prm_CRdciDefaultMenuSel(void);
ImpTypeValCRdciDeltaPLR Stub_Rte_Prm_CRdciDeltaPLR(void);
ImpTypeValCRdciDispConfTimeout Stub_Rte_Prm_CRdciDispConfTimeout(void);
ImpTypeValCRdciDispReset Stub_Rte_Prm_CRdciDispReset(void);
ImpTypeValCRdciDpToIPmin Stub_Rte_Prm_CRdciDpToIPmin(void);
ImpTypeValCRdciDtAmbPrewarn Stub_Rte_Prm_CRdciDtAmbPrewarn(void);
ImpTypeValCRdciEcoRcpEnable Stub_Rte_Prm_CRdciEcoRcpEnable(void);
ImpTypeValCRdciErfsEnable Stub_Rte_Prm_CRdciErfsEnable(void);
ImpTypeValCRdciErfsPlacardSource Stub_Rte_Prm_CRdciErfsPlacardSource(void);
Rte_CtApHufTpmsSWC_PiCalPrmRDCi_R_Calprm_CRdciErfsReifenEco_FncRetPtrType Stub_Rte_Prm_CRdciErfsReifenEco(void);
ImpTypeValCRdciFastDeflateEnable Stub_Rte_Prm_CRdciFastDeflateEnable(void);
Rte_CtApHufTpmsSWC_PiCalPrmRDCi_R_Calprm_CRdciLearnLocateConfig_FncRetPtrType Stub_Rte_Prm_CRdciLearnLocateConfig(void);
ImpTypeValCRdciLongHoldTime Stub_Rte_Prm_CRdciLongHoldTime(void);
ImpTypeValCRdciMaxCorRcp Stub_Rte_Prm_CRdciMaxCorRcp(void);
ImpTypeValCRdciMaxCorTime Stub_Rte_Prm_CRdciMaxCorTime(void);
ImpTypeValCRdciMaxThreshold Stub_Rte_Prm_CRdciMaxThreshold(void);
ImpTypeValCRdciMinRcpFa Stub_Rte_Prm_CRdciMinRcpFa(void);
ImpTypeValCRdciMinRcpRa Stub_Rte_Prm_CRdciMinRcpRa(void);
ImpTypeValCRdciNumPrewarnDetect Stub_Rte_Prm_CRdciNumPrewarnDetect(void);
ImpTypeValCRdciPInitRangeMax Stub_Rte_Prm_CRdciPInitRangeMax(void);
ImpTypeValCRdciPanneBefPos Stub_Rte_Prm_CRdciPanneBefPos(void);
ImpTypeValCRdciPanneTh Stub_Rte_Prm_CRdciPanneTh(void);
ImpTypeValCRdciPrewarnEnable Stub_Rte_Prm_CRdciPrewarnEnable(void);
ImpTypeValCRdciPrewarnIgnition Stub_Rte_Prm_CRdciPrewarnIgnition(void);
ImpTypeValCRdciResetPlausi Stub_Rte_Prm_CRdciResetPlausi(void);
ImpTypeValCRdciRidEnable Stub_Rte_Prm_CRdciRidEnable(void);
ImpTypeValCRdciSensorForeignAkRdk Stub_Rte_Prm_CRdciSensorForeignAkRdk(void);
ImpTypeValCRdciSensorLocSync Stub_Rte_Prm_CRdciSensorLocSync(void);
ImpTypeValCRdciShortHoldTime Stub_Rte_Prm_CRdciShortHoldTime(void);
ImpTypeValCRdciStatInit Stub_Rte_Prm_CRdciStatInit(void);
ImpTypeValCRdciTPrewarnNc Stub_Rte_Prm_CRdciTPrewarnNc(void);
ImpTypeValCRdciTRefShift Stub_Rte_Prm_CRdciTRefShift(void);
ImpTypeValCRdciThCTol Stub_Rte_Prm_CRdciThCTol(void);
ImpTypeValCRdciThNCTol Stub_Rte_Prm_CRdciThNCTol(void);
ImpTypeValCRdciTimeoutPrewarn Stub_Rte_Prm_CRdciTimeoutPrewarn(void);
ImpTypeValCRdciTpmsMarket Stub_Rte_Prm_CRdciTpmsMarket(void);
Rte_CtApHufTpmsSWC_PiCalPrmRDCi_R_Calprm_CRdciTrefSeasAdjConfig_FncRetPtrType Stub_Rte_Prm_CRdciTrefSeasAdjConfig(void);
ImpTypeValCRdciTrefSeasonalAdjustment Stub_Rte_Prm_CRdciTrefSeasonalAdjustment(void);
ImpTypeValCRdciTyrIdFiltGw Stub_Rte_Prm_CRdciTyrIdFiltGw(void);
ImpTypeValCRdciUiaThC Stub_Rte_Prm_CRdciUiaThC(void);
ImpTypeValCRdciUiaThNc Stub_Rte_Prm_CRdciUiaThNc(void);
ImpTypeValCRdciUiwThC Stub_Rte_Prm_CRdciUiwThC(void);
ImpTypeValCRdciUiwThNc Stub_Rte_Prm_CRdciUiwThNc(void);
ImpTypeValCRdciXminCoolTire Stub_Rte_Prm_CRdciXminCoolTire(void);
ImpTypeVal_C_Funktion_ReifenPannenerkennung_aktiv_e Stub_Rte_Prm_C_Funktion_ReifenPannenerkennung_aktiv_e(void);

ImpTypeValCRdciSpeedCcmEnable Stub_Rte_Prm_CRdciSpeedCcmEnable(void);
ImpTypeValCRdciSpeedCcmHyst Stub_Rte_Prm_CRdciSpeedCcmHyst(void);
ImpTypeValCRdciSpeedCcmPressOffsetFa Stub_Rte_Prm_CRdciSpeedCcmPressOffsetFa(void);
ImpTypeValCRdciSpeedCcmPressOffsetRa Stub_Rte_Prm_CRdciSpeedCcmPressOffsetRa(void);
ImpTypeValCRdciSpeedCcmTh Stub_Rte_Prm_CRdciSpeedCcmTh(void);
ImpTypeValCRdciSpeedCcmTime Stub_Rte_Prm_CRdciSpeedCcmTime(void);

ImpTypeValCRdciParkSupExtParkSupConfig Stub_Rte_Prm_CRdciParkSupExtParkSupConfig(void);
ImpTypeValCRdciParkSupMobilityLossThresholdValue Stub_Rte_Prm_CRdciParkSupMobilityLossThresholdValue(void);
ImpTypeValCRdciParkSupNotificationThresholdValueC Stub_Rte_Prm_CRdciParkSupNotificationThresholdValueC(void);
ImpTypeValCRdciParkSupNotificationThresholdValueNc Stub_Rte_Prm_CRdciParkSupNotificationThresholdValueNc(void);
ImpTypeValCRdciParkSupTolNoTempComp Stub_Rte_Prm_CRdciParkSupTolNoTempComp(void);
ImpTypeValCRdciParkSupTolTempComp Stub_Rte_Prm_CRdciParkSupTolTempComp(void);
ImpTypeValCRdciParkSupWarningThresholdValueC Stub_Rte_Prm_CRdciParkSupWarningThresholdValueC(void);
ImpTypeValCRdciParkSupWarningThresholdValueNc Stub_Rte_Prm_CRdciParkSupWarningThresholdValueNc(void);

#ifdef __cplusplus
}
#endif

#endif
