#include "JumpTable.h"

const RDCi_FunctiontableType RDCi_Functiontable = {
      &RCyclicRDCiTask
   ,  &RInitRDCiStartup
   ,  &RExitRDCiBye
   ,  &ROpInvDcmDiagFunktionenReifendruckkontrolle_ConditionCheckRead
   ,  &ROpInvDcmDiagFunktionenReifendruckkontrolle_ReadData
   ,  &ROpInvDcmDiagRdcAktuelleAussentemperatur_ConditionCheckRead
   ,  &ROpInvDcmDiagRdcAktuelleAussentemperatur_ReadData
   ,  &ROpInvDcmDiagRdcAussendruck_ConditionCheckRead
   ,  &ROpInvDcmDiagRdcAussendruck_ReadData
   ,  &ROpInvDcmDiagRdcInaktivStatus_ConditionCheckRead
   ,  &ROpInvDcmDiagRdcInaktivStatus_ReadData
   ,  &ROpInvDcmDiagRdcKalibrierungStatus_ConditionCheckRead
   ,  &ROpInvDcmDiagRdcKalibrierungStatus_ReadData
   ,  &ROpInvDcmDiagRdcKonfiguration_ConditionCheckRead
   ,  &ROpInvDcmDiagRdcKonfiguration_ReadData
   ,  &ROpInvDcmDiagRdcPosition_ConditionCheckRead
   ,  &ROpInvDcmDiagRdcPosition_ReadData
   ,  &ROpInvDcmDiagRdcReferenzAussentemperatur_ConditionCheckRead
   ,  &ROpInvDcmDiagRdcReferenzAussentemperatur_ReadData
   ,  &ROpInvDcmDiagRdcReifendruckHl_ConditionCheckRead
   ,  &ROpInvDcmDiagRdcReifendruckHl_ReadData
   ,  &ROpInvDcmDiagRdcReifendruckHr_ConditionCheckRead
   ,  &ROpInvDcmDiagRdcReifendruckHr_ReadData
   ,  &ROpInvDcmDiagRdcReifendruckVl_ConditionCheckRead
   ,  &ROpInvDcmDiagRdcReifendruckVl_ReadData
   ,  &ROpInvDcmDiagRdcReifendruckVr_ConditionCheckRead
   ,  &ROpInvDcmDiagRdcReifendruckVr_ReadData
   ,  &ROpInvDcmDiagRdcReifentemperaturHl_ConditionCheckRead
   ,  &ROpInvDcmDiagRdcReifentemperaturHl_ReadData
   ,  &ROpInvDcmDiagRdcReifentemperaturHr_ConditionCheckRead
   ,  &ROpInvDcmDiagRdcReifentemperaturHr_ReadData
   ,  &ROpInvDcmDiagRdcReifentemperaturVl_ConditionCheckRead
   ,  &ROpInvDcmDiagRdcReifentemperaturVl_ReadData
   ,  &ROpInvDcmDiagRdcReifentemperaturVr_ConditionCheckRead
   ,  &ROpInvDcmDiagRdcReifentemperaturVr_ReadData
   ,  &ROpInvDcmDiagRdcSensorHersteller_ConditionCheckRead
   ,  &ROpInvDcmDiagRdcSensorHersteller_ReadData
   ,  &ROpInvDcmDiagRdcSolldruckHinten_ConditionCheckRead
   ,  &ROpInvDcmDiagRdcSolldruckHinten_ReadData
   ,  &ROpInvDcmDiagRdcSolldruckVorn_ConditionCheckRead
   ,  &ROpInvDcmDiagRdcSolldruckVorn_ReadData
   ,  &ROpInvDcmDiagRdcStatus_ConditionCheckRead
   ,  &ROpInvDcmDiagRdcStatus_ReadData
   ,  &ROpInvDcmRdcAnlernenLokalisierungLesen_ConditionCheckRead
   ,  &ROpInvDcmRdcAnlernenLokalisierungLesen_ReadData
   ,  &ROpInvDcmRdcErfsEcoTabelleLesen_ConditionCheckRead
   ,  &ROpInvDcmRdcErfsEcoTabelleLesen_ReadData
   ,  &ROpInvDcmRdcHsInaktivereignis_ConditionCheckRead
   ,  &ROpInvDcmRdcHsInaktivereignis_ReadData
   ,  &ROpInvDcmRdcHsKalibrierereignis_ConditionCheckRead
   ,  &ROpInvDcmRdcHsKalibrierereignis_ReadData
   ,  &ROpInvDcmRdcHsWarnereignis1_ConditionCheckRead
   ,  &ROpInvDcmRdcHsWarnereignis1_ReadData
   ,  &ROpInvDcmRdcHsWarnereignis2_ConditionCheckRead
   ,  &ROpInvDcmRdcHsWarnereignis2_ReadData
   ,  &ROpInvDcmRdcHsWarnereignis3_ConditionCheckRead
   ,  &ROpInvDcmRdcHsWarnereignis3_ReadData
   ,  &ROpInvDcmRdcHsWarnereignisRuecknahme_ConditionCheckRead
   ,  &ROpInvDcmRdcHsWarnereignisRuecknahme_ReadData
   ,  &ROpInvDcmRdcHsWarnereignisWeich1_ConditionCheckRead
   ,  &ROpInvDcmRdcHsWarnereignisWeich1_ReadData
   ,  &ROpInvDcmRdcHsWarnereignisWeich2_ConditionCheckRead
   ,  &ROpInvDcmRdcHsWarnereignisWeich2_ReadData
   ,  &ROpInvDcmRdcHsWarnereignisWeich3_ConditionCheckRead
   ,  &ROpInvDcmRdcHsWarnereignisWeich3_ReadData
   ,  &ROpInvDcmRdcMessdatenblock1_ConditionCheckRead
   ,  &ROpInvDcmRdcMessdatenblock1_ReadData
   ,  &ROpInvDcmRdcMessdatenblock2_ConditionCheckRead
   ,  &ROpInvDcmRdcMessdatenblock2_ReadData
   ,  &ROpInvDcmRdcMessdatenblock3_ConditionCheckRead
   ,  &ROpInvDcmRdcMessdatenblock3_ReadData
   ,  &ROpInvDcmRdcMessdatenblock4_ConditionCheckRead
   ,  &ROpInvDcmRdcMessdatenblock4_ReadData
   ,  &ROpInvDcmRdcRidAktReifenLaufstreckeLesen_ConditionCheckRead
   ,  &ROpInvDcmRdcRidAktReifenLaufstreckeLesen_ReadData
   ,  &ROpInvDcmRdcRidAktReifenQrCodeLesen_ConditionCheckRead
   ,  &ROpInvDcmRdcRidAktReifenQrCodeLesen_ReadData
   ,  &ROpInvDcmRdcRidAlteReifenLaufstreckeLesen_ConditionCheckRead
   ,  &ROpInvDcmRdcRidAlteReifenLaufstreckeLesen_ReadData
   ,  &ROpInvDcmRdcRidAlteReifenQrCodeLesen_ConditionCheckRead
   ,  &ROpInvDcmRdcRidAlteReifenQrCodeLesen_ReadData
   ,  &ROpInvDcmStatusRdcDeveloperDataLesen_ConditionCheckRead
   ,  &ROpInvDcmStatusRdcDeveloperDataLesen_ReadData
   ,  &ROpInvDcmStatusRdcErfsAktReifenEcoLesen_ConditionCheckRead
   ,  &ROpInvDcmStatusRdcErfsAktReifenEcoLesen_ReadData
   ,  &ROpInvDcmStatusRdcErfsAktReifenLesen_ConditionCheckRead
   ,  &ROpInvDcmStatusRdcErfsAktReifenLesen_ReadData
   ,  &ROpInvDcmStatusRdcErfsTsaDatenLesen_ConditionCheckRead
   ,  &ROpInvDcmStatusRdcErfsTsaDatenLesen_ReadData
   ,  &ROpInvDcmStatusRdcLesen_ConditionCheckRead
   ,  &ROpInvDcmStatusRdcLesen_ReadData
   ,  &ROpInvDcmStatusRdcVersion_ConditionCheckRead
   ,  &ROpInvDcmStatusRdcVersion_ReadData
   ,  &ROpInvDcmStatusReLesenDruckcodierung_ConditionCheckRead
   ,  &ROpInvDcmStatusReLesenDruckcodierung_ReadData
   ,  &ROpInvDcmSteuernDigitalRdc_WriteData
   ,  &ROpInvDcmSteuernRadelektronikVorgeben_WriteData
   ,  &ROpInvDcmSteuernRdcDeveloperConfig_WriteData
   ,  &ROpInvDcmSteuernRdcErfsDeveloperConfig_WriteData
   ,  &ROpInvDcmSteuernRdcErfsEcoAktReifenPosVorgeben_WriteData
   ,  &ROpInvDcmSteuernRdcErfsEcoNeueReifenVorgeben_WriteData
   ,  &ROpInvDcmSteuernRdcErfsEcoReifentabelleVorgeben_WriteData
   ,  &ROpInvDcmSteuernRdcErfsTsaDatenVorgeben_WriteData
   ,  &ROpInvDemErrorRdci1To3WrongWuMounted_InitMonitorForEvent
   ,  &ROpInvDemErrorRdci4WrongWuMounted_InitMonitorForEvent
   ,  &ROpInvDemErrorRdciATempInvalid_InitMonitorForEvent
   ,  &ROpInvDemErrorRdciATempTimeout_InitMonitorForEvent
   ,  &ROpInvDemErrorRdciAusfall_InitMonitorForEvent
   ,  &ROpInvDemErrorRdciAutoLearningFailed_InitMonitorForEvent
   ,  &ROpInvDemErrorRdciBefuellhinweis_InitMonitorForEvent
   ,  &ROpInvDemErrorRdciConVehAlive_InitMonitorForEvent
   ,  &ROpInvDemErrorRdciConVehCrc_InitMonitorForEvent
   ,  &ROpInvDemErrorRdciConVehInvalid_InitMonitorForEvent
   ,  &ROpInvDemErrorRdciConVehTimeout_InitMonitorForEvent
   ,  &ROpInvDemErrorRdciDruckwarnung_InitMonitorForEvent
   ,  &ROpInvDemErrorRdciEinheitenBn2020Invalid_InitMonitorForEvent
   ,  &ROpInvDemErrorRdciEinheitenBn2020Timeout_InitMonitorForEvent
   ,  &ROpInvDemErrorRdciErfsCodingDataInconsistent_InitMonitorForEvent
   ,  &ROpInvDemErrorRdciGatewayOrAntennaError_InitMonitorForEvent
   ,  &ROpInvDemErrorRdciKalibrierung_InitMonitorForEvent
   ,  &ROpInvDemErrorRdciOtherWuSensorType_InitMonitorForEvent
   ,  &ROpInvDemErrorRdciPannenwarnung_InitMonitorForEvent
   ,  &ROpInvDemErrorRdciPartialSystemAvailability_InitMonitorForEvent
   ,  &ROpInvDemErrorRdciRdcDtPckg1Alive_InitMonitorForEvent
   ,  &ROpInvDemErrorRdciRdcDtPckg1Invalid_InitMonitorForEvent
   ,  &ROpInvDemErrorRdciRdcDtPckg1Timeout_InitMonitorForEvent
   ,  &ROpInvDemErrorRdciRelativzeitInvalid_InitMonitorForEvent
   ,  &ROpInvDemErrorRdciRelativzeitTimeout_InitMonitorForEvent
   ,  &ROpInvDemErrorRdciRfExternalInterference_InitMonitorForEvent
   ,  &ROpInvDemErrorRdciSystemNotAvailable_InitMonitorForEvent
   ,  &ROpInvDemErrorRdciTpmsManufactoryMode_InitMonitorForEvent
   ,  &ROpInvDemErrorRdciUnspecifiedWfcDefect_InitMonitorForEvent
   ,  &ROpInvDemErrorRdciUnspecifiedWuMute_InitMonitorForEvent
   ,  &ROpInvDemErrorRdciVVehAliveFailure_InitMonitorForEvent
   ,  &ROpInvDemErrorRdciVVehCogInvalid_InitMonitorForEvent
   ,  &ROpInvDemErrorRdciVVehCogQualifier_InitMonitorForEvent
   ,  &ROpInvDemErrorRdciVVehCrcFailure_InitMonitorForEvent
   ,  &ROpInvDemErrorRdciVVehTimeout_InitMonitorForEvent
   ,  &ROpInvDemErrorRdciWarnruecknahme_InitMonitorForEvent
   ,  &ROpInvDemErrorRdciWuDefectFl_InitMonitorForEvent
   ,  &ROpInvDemErrorRdciWuDefectFr_InitMonitorForEvent
   ,  &ROpInvDemErrorRdciWuDefectRl_InitMonitorForEvent
   ,  &ROpInvDemErrorRdciWuDefectRr_InitMonitorForEvent
   ,  &ROpInvDemErrorRdciWuLocalisationFailed_InitMonitorForEvent
   ,  &ROpInvDemErrorRdciWuLowBatteryFl_InitMonitorForEvent
   ,  &ROpInvDemErrorRdciWuLowBatteryFr_InitMonitorForEvent
   ,  &ROpInvDemErrorRdciWuLowBatteryRl_InitMonitorForEvent
   ,  &ROpInvDemErrorRdciWuLowBatteryRr_InitMonitorForEvent
   ,  &ROpInvDemErrorRdciWuMuteFl_InitMonitorForEvent
   ,  &ROpInvDemErrorRdciWuMuteFr_InitMonitorForEvent
   ,  &ROpInvDemErrorRdciWuMuteRl_InitMonitorForEvent
   ,  &ROpInvDemErrorRdciWuMuteRr_InitMonitorForEvent
   ,  &ROpInvNvmRdciCommonBlock_NvMNotifyJobFinished_JobFinished
   ,  &ROpInvNvmRdciDiagBlock1_NvMNotifyJobFinished_JobFinished
   ,  &ROpInvNvmRdciDiagBlock2_NvMNotifyJobFinished_JobFinished
   ,  &ROpInvNvmRdciErfsBlock_NvMNotifyJobFinished_JobFinished
   ,  &ROpInvNvmRdciErfsEcoBlock_NvMNotifyJobFinished_JobFinished
   ,  &ROpInvNvmRdciErfsTsaBlock_NvMNotifyJobFinished_JobFinished
   ,  &ROpInvNvmRdciRidQrBlock1_NvMNotifyJobFinished_JobFinished
   ,  &ROpInvNvmRdciRidQrBlock2_NvMNotifyJobFinished_JobFinished
   ,  &ROpInvNvmRdciWarnStatusBlock_NvMNotifyJobFinished_JobFinished
   ,  &ROpInvNvmRdciZoHistoryBlock_NvMNotifyJobFinished_JobFinished
   ,  &ROpInvNvmRdciZomBlock1_NvMNotifyJobFinished_JobFinished
   ,  &ROpInvNvmRdciZomBlock2_NvMNotifyJobFinished_JobFinished
   ,  &ROpInvNvmRdciCommonBlock_NvMNotifyInitBlock_InitBlock
   ,  &ROpInvNvmRdciDiagBlock1_NvMNotifyInitBlock_InitBlock
   ,  &ROpInvNvmRdciDiagBlock2_NvMNotifyInitBlock_InitBlock
   ,  &ROpInvNvmRdciErfsBlock_NvMNotifyInitBlock_InitBlock
   ,  &ROpInvNvmRdciErfsEcoBlock_NvMNotifyInitBlock_InitBlock
   ,  &ROpInvNvmRdciErfsTsaBlock_NvMNotifyInitBlock_InitBlock
   ,  &ROpInvNvmRdciRidQrBlock1_NvMNotifyInitBlock_InitBlock
   ,  &ROpInvNvmRdciRidQrBlock2_NvMNotifyInitBlock_InitBlock
   ,  &ROpInvNvmRdciWarnStatusBlock_NvMNotifyInitBlock_InitBlock
   ,  &ROpInvNvmRdciZoHistoryBlock_NvMNotifyInitBlock_InitBlock
   ,  &ROpInvNvmRdciZomBlock1_NvMNotifyInitBlock_InitBlock
   ,  &ROpInvNvmRdciZomBlock2_NvMNotifyInitBlock_InitBlock
   ,  &ROpInvDcmStatusRdcExtParkSupervisionLesen_ConditionCheckRead
   ,  &ROpInvDcmStatusRdcExtParkSupervisionLesen_ReadData
};
