

#ifdef RTE_START_SEC_CODE
# undef RTE_START_SEC_CODE
#define START_SEC_CODE
#endif

#ifdef RTE_START_SEC_CONST_UNSPECIFIED
# undef RTE_START_SEC_CONST_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif

#ifdef RTE_STOP_SEC_CODE
# undef RTE_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef RTE_STOP_SEC_CONST_UNSPECIFIED
# undef RTE_STOP_SEC_CONST_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#ifdef RTE_START_SEC_CTAPHUFTPMSSWC_APPL_CODE
# undef RTE_START_SEC_CTAPHUFTPMSSWC_APPL_CODE
#define START_SEC_CODE
#endif

#ifdef RTE_STOP_SEC_CTAPHUFTPMSSWC_APPL_CODE
# undef RTE_STOP_SEC_CTAPHUFTPMSSWC_APPL_CODE
#define STOP_SEC_CODE
#endif

#ifdef RTE_START_SEC_CONST_DEFAULT_RTE_CALPRM_GROUP_UNSPECIFIED
# undef RTE_START_SEC_CONST_DEFAULT_RTE_CALPRM_GROUP_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif

#ifdef RTE_STOP_SEC_CONST_DEFAULT_RTE_CALPRM_GROUP_UNSPECIFIED
# undef RTE_STOP_SEC_CONST_DEFAULT_RTE_CALPRM_GROUP_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#ifdef RTE_START_SEC_VAR_DEFAULT_RTE_PIM_GROUP_UNSPECIFIED
# undef RTE_START_SEC_VAR_DEFAULT_RTE_PIM_GROUP_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif

#ifdef RTE_STOP_SEC_VAR_DEFAULT_RTE_PIM_GROUP_UNSPECIFIED
# undef RTE_STOP_SEC_VAR_DEFAULT_RTE_PIM_GROUP_UNSPECIFIED
#define STOP_SEC_VAR
#endif

